### PR TITLE
Reorder the xlC command line used for linking

### PR DESCRIPTION
**Pull request by zorts**
Reorder the xlC command line used for linking to put options with flags ahead of files to be processed

### CODE REVIEW

**Comment by gibfahn** [comment]
Fixes: https://github.com/ibmruntimes/node/issues/85

cc/ @ibmruntimes/s390

**Comment by jBarz** [comment]
LGTM

**Comment by bnoordhuis** [comment]
This looks like it should go into https://github.com/nodejs/node-gyp.  I'll review if someone opens a pull request.

**Comment by zorts** [comment]
I'm not sure what the process is; this *is* a pull request, isn't it?

**Comment by jBarz** [comment]
I will first merge this pull request into our ibmruntimes repo.
I will eventually upstream this together with all the other z/OS changes into the official node-gyp repo as [suggested](https://github.com/ibmruntimes/node/pull/86#issuecomment-292545176)

**Pull request merged**
